name: Cleanup Sentry

on:
  workflow_dispatch:
  schedule:
  - cron: "0 3 * * *"

permissions:
  contents: read

env:
  SENTRY_TOKEN: ${{ secrets.SENTRY_MAINTENANCE_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run cleanup
      run: |
        python main.py

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
